services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: nginx_dev
    depends_on:
      - python
    environment:
      PYTHON_BACKEND: python
    volumes:
      - "./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:cached"
    ports:
      - ${FRONT_PORT:-5000}:80
